name: Build and Publish to Docker
on:
    push:
        branches:
            - main
        paths:
            - Api/**
    workflow_dispatch:
jobs:
    push_to_registry:
        name: Push Docker Image to Docker Hub
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
          - name: Check out the repo
            uses: actions/checkout@v4

          - name: Pwd
            run: |
                pwd
                ls

          - name: Log in to Docker
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: lockermanwxlf/azure_terraform_sample

          - name: Build and push to Docker
            uses: docker/build-push-action@v5
            with:
                context: .
                file: ./Api/Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
